# -*- coding: utf-8 -*-
"""flask_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MrCQnyYg8JQraeoB6Wt3hBLhmZMSrzFi
"""

from flask import Flask, render_template, request
import pickle
import subprocess

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        # Get uploaded text file
        uploaded_file = request.files["file"]
        if uploaded_file.filename != "":
            full_text = uploaded_file.read().decode("utf-8")

            # Save the uploaded text to a temporary file
            with open("uploaded_text.txt", "w") as f:
                f.write(full_text)

            # Run the NLP processing code using subprocess
            subprocess.run(["python", "nlp_processing_code.pkl"])

            # Load the processed results
            with open("processed_results.pkl", "rb") as f:
                processed_results = pickle.load(f)

            return render_template("results.html", **processed_results)

    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)